### ISSUE TITLE
Test code duplication issue

### ISSUE THREAD

**Issue by karlosmid** [arp242/arp242.net#11]
Hi, great post!

Here I would like to point out one important benefit of tiny unit test code, and not just having Integration tests. When code is changed and unit test fails, the error is more close to the source code that caused the error.

In integration test, you need to spend more time to figure it out the cause.
As you stated,  this creates duplicate testing code, but I think that the tradeoff is reasonable.

Very similar when you need to put input verification checks both on client and server side. It is duplicate check, but in order to satisfy security features, it is a must.

I like very much the idea of making blog comments as github issue.

Regards, Karlo.

**Comment by Carpetsmoker** [comment]
Yeah, I think unit tests can definitely add value for this, I think it depends on what you're doing and the complexity of it, how much duplication you're adding, as well as how much effort/abstraction it takes to add a unit test (sometimes it's easy, other times ... not so much).

I think unit tests can also be very useful as a development tool, as it gives you quick and direct feedback.

> Very similar when you need to put input verification checks both on client and server side. It is duplicate check, but in order to satisfy security features, it is a must.

Funny you mention this example, as I wrote an article about this exact thing a few weeks ago. My view is that the frontend checks are mostly redundant, and should be removed in most cases (my point is a bit longer than that, I'll try and finish it up this week).
