### ISSUE TITLE
About s/mime

### ISSUE THREAD

**Issue by GTP95** [arp242/arp242.net#13]
In your article about signing emails in the paragraph about s/mime you wrote: 
"The downside of this is that anyone can sign their emails with a valid key, which isn’t necessarily telling you much (just because haxx0r.ru has a certificate doesn’t mean it’s trustworthy)".
How is this difrerent from PGP? In PGP too everyone can have a valid key, in both systems the point is that they let you verify who owns the key/certificate, so if you receive a message claiming to be from Amazon but the PGP key or the certificate belongs to haxx0r.ru you know that it's a phishing attempt.

**Comment by Carpetsmoker** [comment]
The difference is that if I try to verify a message signed with a PGP signature and my system doesn't know the signature, it will display an error that it's an unknown signature.

With S/MIME the standard certificate chain is used, like with HTTPS. If the chain is valid the signature will be accepted as valid, like with https.

This is subtly but markedly different; with the PGP model I need to explicitly tell the system what to trust, whereas with the S/MIME model this trust is deferred to the CA organisations. In practice, anyone can get a certificate from a CA so it's not particularly valid for verifying authenticity (it's still useful for encryption, but that's an entire different use case).

Many emails are already signed with DKIM today, which is more-or-less the same model as S/MIME (and with the same lack of verification of the actual sender, too).

So how I envision how it could work is that once I sign up for Amazon.com I get a page or email saying "Yo, welcome to your service, here's our public key, please add it so you know all future emails are genuine, and don't trust anything not signed with this". As far as I know, you can't really do that with S/MIME, just as you can't really with HTTPS.

**Comment by GTP95** [comment]
Thanks for the clarification. You're right, to obtain the same result of PGP with S/MIME is required an additional step: verify manually that the subject that has obtained the certificate matches to who he is claming to be in the email. So in this regard PGP has a simpler workflow.Il 17 Mar 2019 09:22, Martin Tournoij <notifications@github.com> ha scritto:The difference is that if I try to verify a message signed with a PGP signature and my system doesn't know the signature, it will display an error that it's an unknown signature.
With S/MIME the standard certificate chain is used, like with HTTPS. If the chain is valid the signature will be accepted as valid, like with https.
This is subtly but markedly different; with the PGP model I need to explicitly tell the system what to trust, whereas with the S/MIME model this trust is deferred to the CA organisations. In practice, anyone can get a certificate from a CA so it's not particularly valid for verifying authenticity (it's still useful for encryption, but that's an entire different use case).
Many emails are already signed with DKIM today, which is more-or-less the same model as S/MIME (and with the same lack of verification of the actual sender, too).
So how I envision how it could work is that once I sign up for Amazon.com I get a page or email saying "Yo, welcome to your service, here's our public key, please add it so you know all future emails are genuine, and don't trust anything not signed with this". As far as I know, you can't really do that with S/MIME, just as you can't really with HTTPS.
