### ISSUE TITLE
Translation permission

### ISSUE THREAD

**Issue by Fragalli** [arp242/arp242.net#14]
Hi, i just read your article about YAML files and find it awesome !

Can i translate to Brazilian Portuguese ?

**Comment by Carpetsmoker** [comment]
Sure; I'd be honoured :-) Let me know the link and I'll add it.

You don't really need my permission btw. All my writings are available under [CC-BY](https://creativecommons.org/licenses/by/4.0/), which basically means you can do with it as you want, as long as you attribute the original to me.

**Comment by arp242** [comment]
I'll close this issue for now so it's off the "open issues" list, but feel free to get back to me via this issue or email.
