### ISSUE TITLE
No need for the ‘Do Not Track’ section in your post.

### ISSUE THREAD

**Issue by Caspy7** [arp242/arp242.net#2]
Reading this post https://arp242.net/weblog/browsers-conflict-interest.html and it's pretty good and I agree with it - except for the section on Do Not Track.

I don't understand the point being made by it. The screenshot you provide of their notification does not seem inaccurate or scaremongering or somehow negatively influential. 

In reality nowadays very few entities honor DNT and it makes users *more easily* fingerprinted. That is to say, it makes it easier for the bad guys to track you. For those reasons I don't recommend it to people.

**Comment by arp242** [comment]
Sorry for taking so long in getting back to this. I remove this section now.

> In reality nowadays very few entities honor DNT and it makes users more easily fingerprinted. That is to say, it makes it easier for the bad guys to track you. For those reasons I don't recommend it to people.

Yes, I agree. I actually wrote a separate article about DNT today: https://www.arp242.net/dnt.html

**Comment by loleg** [comment]
15 years after enabling and encouraging [DNT adoption](https://blog.mozilla.org/metrics/2011/09/08/understanding-dnt-adoption-within-firefox/), Mozilla has removed the the feature according to [Windows Report](https://windowsreport.com/mozilla-firefox-removes-do-not-track-feature-support-heres-what-it-means-for-your-privacy/). I expect we'll see an official post on their [netpolicy blog](https://blog.mozilla.org/netpolicy/) soon. Thank you for being a visionary `;-)`
