### ISSUE TITLE
If thats the main reason why you like jquery so much why not use zepto?

### ISSUE THREAD

**Issue by hitautodestruct** [arp242/arp242.net#22]
In your jquery.html article you don't mention zepto which is basically jquuery just without all the legacy browser support.

https://zeptojs.com/

**Comment by arp242** [comment]
I never tried it, and have no opinion on it either way.

It doesn't seem to get many updates though: https://github.com/madrobby/zepto/commits/master and PRs/issues seem to go unaddressed. jQuery seems to be doing better there.

jQuery is also "standard": many people already know it. That, on its own, is a good advantage IMHO.

Like I said, I have no strong opinions. That's just a quick impression.

**Comment by hitautodestruct** [comment]
It's a jquery standard compliant library, so nothing should surprise you.
But that lack of updates is quite sad and makes sense not to use it because of that.

I agree with the points you made in the article.
But, I think the main YMNNJQ movement was when everybody used jquery for everything and it was very much overkill but it was included in every project just for the sake of 1 or two convenience dom methods.

**Comment by arp242** [comment]
Thanks. I'll give it a try when I got some time.

> I think the main YMNNJQ movement was when everybody used jquery for everything and it was very much overkill but it was included in every project just for the sake of 1 or two convenience dom methods.

Yeah, maybe. I actually worked on a "jQuery-ish" library which had a dependency tree between all the functions, and you could select a version which only used what you needed, and nothing more.

On the other hand, it's often easy to get these kind of convenience methods wrong if you're not careful, so there is still some value in using jQuery.

I also wish jQuery was written in a way that allowed easier copy/pasting things out of it :-(

**Comment by arp242** [comment]
I had another look, and Zepto seems unmaintained with several bugs open. PRs are not being responded to. jQuery still seems the better choice to me, and all that switching to Zepto gives me is a ~15K saving, which seems like "yak shaving" to me.

**Comment by hitautodestruct** [comment]
Zepto also defaults to using native methods removing non modern browser support.
So, it's speedier than jQuery.

But, alas, if it's unmaintained there's not much point in using it going forward :-(

**Comment by arp242** [comment]
In general, jQuery seems pretty hawkish about removing workarounds/hacks for older browsers, see e.g.  https://github.com/jquery/jquery/pull/4569 and https://github.com/jquery/jquery/issues/4568. jQuery only supports browsers in actual use, which unfortunately includes some "non-modern" browsers (like IE11), but I can't control the browsers people use, so I think that's a good choice. I had a discussion about this over here a few weeks ago: https://lobste.rs/s/0ovjzc/on_let_vs_const#c_v4qyh5

A number of jQuery methods use native methods too, e.g. `jQuery.trim()` [always calls `"".trim()`](https://github.com/jquery/jquery/blob/d0ce00cdfa680f1f0c38460bc51ea14079ae8b07/src/var/trim.js), although I didn't do a complete side-by-side comparison with Zepto here. In my experience, jQuery is more than "fast enough" for most applications. Certainly in my own applications it's never been a bottleneck or significant source of memory leaks. That being said, it's probably not a good choice for extremely heavy DOM manipulations and the like.
