### ISSUE TITLE
Intersting article on problems with YAML, your thoughts on UCL.

### ISSUE THREAD

**Issue by ethoms** [arp242/arp242.net#23]
Hi, thanks for the interesting article. I didn't read it all, but once I stopped to question if I actually like reading YAML, my thoughts:

- I find it weird, coming from a C syntax background, it's a bit alien.
- I like coding in python, but counting white space is not what I want to spend time on.
- Despite  being noisy, I'm used to curly brackets and semi-colons.

So I stumbled on your article when deciding on a config format for a big project I'm working on. It's heavily geared to FreeBSD where UCL is more considered. Some developers are trying to port the varying and inconsistent system config file formats to UCL, but that's about as easy as IPv6 adoption. UCl is inspired by the nginx config (I think).

Anyways, I decided to go with UCL. There's a nice shell command utility to work with UCL configs by the name of 'uclcmd'. It leverages the official libucl library (link below). One great thing about UCL (libucl) is that it exports to YAML and JSON and looks pretty solid and performant. I was trying to find out how good UCL was for serialization vs YAML.

Perhaps you could take a look at UCL and make an article of your impressions of it.

https://github.com/vstakhov/libucl

**Comment by arp242** [comment]
Thanks :-)

I'm familiar with UCL, and it seems like a cool format, but on the other hand, I just read the website and never actually used it in practice. I try to reserve judgement (either positive or negative) for these kind of things until I actually *used* it. It's not so easy as "take a look and write an article about it": without actual hands-on experience it would be lacking in depth.

Also see:

- [JSON as config file](https://github.com/arp242/arp242.net/issues/8#issuecomment-403527157)
- [Add comparison to UCL - universal configuration language as well](https://github.com/arp242/arp242.net/issues/5)
