### ISSUE TITLE
jQuery build without sizzle?

### ISSUE THREAD

**Issue by adamcoulombe** [arp242/arp242.net#27]
You mentioned a 17k jQuery build on your site that doesnt have sizzle?

Im just curious, is that something you build custom or how would you go about including that in a project?

**Comment by arp242** [comment]
Yeah, you need to make a custom jQuery build. Basically, clone the jQuery git repo and run `grunt` with your custom build flags.

For example, from my shell history:

    grunt custom:-ajax/jsonp,-ajax/script,-ajax/parseXML,-css/showHide,-deprecated,-effects,-event/alias,-wrap,-exports/amd,-sizzle

This excludes some stuff I don't use, including `-sizzle`.

See the jQuery README for more docs and more detailed modules you can exclude: https://github.com/jquery/jquery

Hope this helps.

**Comment by adamcoulombe** [comment]
okay, neat. I wonder if there's any way of importing individual modules if using ES6.

for example with lodash, you can import the entire library like like this:
`import _ from 'lodash';`

or if you just want a few things you can:
`import { map, tail, times, uniq } from 'lodash';`

From reading a post on your website today, I share a similar perspective as you when it comes to using jquery. It's not that I can't or don't want to write vanilla JS, but many things are just expressed way more intuitively with jquery.

With that said theres a bunch of stuff I almost never use,  so I'll take a look at custom build. thanks!

**Comment by arp242** [comment]
I don't think that's possible, but I don't use modules (since it doesn't have good enough browser support yet) so not an expert.

**Comment by arp242** [comment]
(Closing because I think your question is answered? Feel free to comment further though)
