### ISSUE TITLE
The Art of Unix Programming, reformatted: fix-taoup.py link broken

### ISSUE THREAD

**Issue by aaaxx** [arp242/arp242.net#30]
I was curious about the cleanup process, but the script is missing, and the GitHub repo search doesn't give me any useful results.

**Comment by arp242** [comment]
I removed it some time ago, as it was actually quite ugly and did a lot of hand-hacking afterwards anyway, but here it is if you're really interested: https://github.com/arp242/arp242.net/commit/1275f52#diff-59cc28d7fb2438f0af48f77c463bd347
