### ISSUE TITLE
DeGPLing European Union Public License

### ISSUE THREAD

**Issue by matkoniecz** [arp242/arp242.net#39]
https://www.arp242.net/license.html is pretty convincing in switching from AGPL to EUPL, but

> Bad: The GPL Compatability is good, but the way it’s worded less so; you can distribute “Derivative Works” as GPL in its entirety, rather than just the changes made. In other words, you can circumvent the stronger copyleft.

European Union Public License has ineffective network protection by default.

Have you managed to solve this problem?

**Comment by arp242** [comment]
I mentioned this at the end:

> the biggest issue is the GPL-compatibility copyleft circumvention but I’ve worked around that by just removing the GPL, MPL and some other licenses from the “Compatible licenses” appendix and adding a note at the top that this list appendix was modified.

**Comment by arp242** [comment]
(I'll close this issue btw, but feel free to respond and I'll still get emails)

**Comment by matkoniecz** [comment]
Right, I am blind again. For reference - see https://github.com/zgoat/goatcounter/blob/master/LICENSE
