### ISSUE TITLE
"Why I’m still using jQuery in 2019" - this article is totall bullshit.

### ISSUE THREAD

**Issue by Mlocik97** [arp242/arp242.net#41]
So about first example:

> Pages like You might not need jQuery try to sell the idea that it’s easy to ditch jQuery, but the very first example is a good reason to use jQuery: one line of trivial jQuery code gets replaced with 10 lines of vanilla JS code!

that 10 lines example is only for IE10+,... IE today is totally dead, and we have fetch() that is as short as writting $.ajax(), well no, it's even one character shorter.

About selectors? You can create one/two line alias for $(), like https://stackoverflow.com/a/46079132

so I think, this whole article is one big bullshit.

Btw. today when we have things like Svelte, usage of something like jQuery should be totally illegal.

Or how would You do this in jQuery? https://svelte.dev/examples#numeric-inputs because in Svelte it's practically without writting any JavaScript at all (well except declaring variables, that is so trivial)... I'm sure You would need to write 20x more code in jQuery...

and even two years ago, it was already bullshit.. all my arguments are correct for 2019 too.

**Comment by arp242** [comment]
> Btw. today when we have things like Svelte, usage of something like jQuery should be totally illegal.

Coolio. Call the police and send me to prison then.
