### ISSUE TITLE
feedback on https://www.arp242.net/jia-tan-go.html

### ISSUE THREAD

**Issue by ldez** [arp242/arp242.net#48]
Hello,

Your article is interesting, I would like to add that the problem can also happen with `testdata` folder name.

It can be more subtle than test filenames because non-test Go code can be used.
For example, inside linters, `testdata` contains "real" code.

I shared with you the idea that GitHub, GitLab, etc. should find a way to display a message about those file names.

**Comment by arp242** [comment]
Code in `testdata` is already compiled; AFAIK there is nothing special about the name "testdata".

And regardless, you still need to actually import and explicitly reference the `testdata` package, which you don't need to with a_test.go.

**Comment by ldez** [comment]
The code in `testdata` is never compiled this is a special name.

The go tool ignores directories starting with `.`, `_`, or named `testdata`.
